{
 "title": "app",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Alloc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "Alloc{instance=\"app:9000\"}"
    },
    {}
   ]
  },
  {
   "title": "FreeMemory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "FreeMemory{instance=\"app:9000\"}"
    },
    {}
   ]
  },
  {
   "title": "PollCount",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "PollCount{instance=\"app:9000\"}"
    },
    {}
   ]
  },
  {
   "title": "PollCount",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "TotalMemory{instance=\"app:9000\"}"
    },
    {}
   ]
  }
 ]
}